{ lib, ... }:
{
  den.aspects.gwen-t1 = {
    coolercontrol-config.text =
      let
        ### Hardware device IDs
        cpu = # 9800X3D
          "3145e1a42801faf9cf948df8c705afb4859f084c10a7e7c5e4efecb1e0167127";
        gpu = # 9070 XT
          "97910386cac9bfce54b2c224e4aaef42cd953440cb57f1ff5ff46ac183bf338e";
        it8696 = # MB fan controller
          "fa49f4645cba12961942172e0455e53675b4adbc2ed077a740863e40266e9803";
        nvme_990pro = # 4TB SSD
          "341fd0f49200232856b962da8ac0e1e21895610be9a6bc48415f27190b412931";
        nvme_970evo = # 1TB SSD
          "62431f8d94059dfab9adce10c509b9beefe28048c4674d7653baeafa72bdb286";
        cust_sens_dev = # Custom sensor device
          "19e098e312e1b1b39163a343ea22b6ea17f18ec1a803ffe0ce44f5bacd6076ee";

        # Disabled/Other
        acpitz = "f42333b13a2853dfb8e516c576470622e74a4659bfffe7ca229f68733beae979";
        gigabyte_wmi = "9a64f7a5c7b59e073064f69eea496b0424b867bb35c843c28825f6d4a73aeba5";
        ethernet = "cf77dfb5a9215ce276b33d7e7d63d5b0334aefe1b00eb6baa333f3c63cec1e14";
        spd_1 = "425f4db3690287aa7dddd4ea2dd5576fb2ec9665ae005115c3dad7ed0b7370ea";
        spd_2 = "fc4182d66cb8b71b330f257eed12cf3efc6e24219b4eeefdcb9b579e07b3f910";
      in
      # Stupid extension... Nix highlighting is close enough to make toml readable
      lib.replaceStrings [ "# syntax: nix\n" ] [ "" ] ''
        # syntax: nix
        ### ------------------------------------------------------
        # COOLERCONTROL CONFIGURATION
        # Generated by NixOS
        ### ------------------------------------------------------

        ###  General Settings ---
        [settings]
        apply_on_boot = true
        liquidctl_integration = true
        hide_duplicate_devices = true
        no_init = false
        startup_delay = 2
        thinkpad_full_speed = false
        compress_payload = false
        poll_rate = 1.0
        drivetemp_suspend = true

        ###  Profiles ---
        [[profiles]]
        uid = "37d94b73-b524-40a3-936a-56e73277722c"
        name = "AIO Fans"
        p_type = "Graph"
        speed_profile = [[0.0, 40], [70.0, 40], [80.0, 50], [85.0, 60], [90.0, 80], [105.0, 80], [106.0, 100]]
        temp_source = { temp_name = "sensor1", device_uid = "${cust_sens_dev}" }
        temp_min = 0.0
        temp_max = 106.0
        function_uid = "02ba5ea0-89cc-4085-808f-c3b1cc97963b"
        offset_profile = []


        ###  Functions ---
        [[functions]]
        uid = "02ba5ea0-89cc-4085-808f-c3b1cc97963b"
        name = "ExpMovAvg"
        f_type = "ExponentialMovingAvg"
        duty_minimum = 2
        duty_maximum = 100
        sample_window = 12

        ###  Device Settings ---
        [device-settings]

        # IT8696 Fan Controller
        [device-settings.${it8696}]
        fan5 = { speed_fixed = 100 }                                    # CPU Pump
        fan1 = { profile_uid = "37d94b73-b524-40a3-936a-56e73277722c" } # Radiator Fans

        ###  Individual Device Configs ---
        # CPU
        [settings.${cpu}]
        name = "AMD Ryzen 7 9800X3D 8-Core Processor"
        disable = false
        [settings.${cpu}.channel_settings]
        temp3 = { label = "CPU Temp Tccd1", disabled = true }
        "CPU Freq Max" = { label = "CPU Freq Max", disabled = true }
        "CPU Freq Avg" = { label = "CPU Freq Avg", disabled = true }
        "CPU Freq Min" = { label = "CPU Freq Min", disabled = true }

        # AMD GPU
        [settings.${gpu}]
        name = "amdgpu"
        disable = false
        [settings.${gpu}.channel_settings]
        freq2 = { label = "GPU Mem", disabled = false }
        fan1 = { label = "GPU Fans", disabled = false, extension = { hw_fan_curve_enabled = true } }
        temp1 = { label = "GPU Temp Edge", disabled = true }
        temp3 = { label = "GPU Temp Mem", disabled = true }

        # ACPITZ
        [settings.${acpitz}]
        name = "acpitz"
        disable = true
        [settings.${acpitz}.channel_settings]

        # IT8696 (Fan Controller)
        [settings.${it8696}]
        name = "it8696"
        disable = false
        [settings.${it8696}.channel_settings]
        fan3 = { label = "Fan3", disabled = false } # NVME Fan
        temp4 = { label = "Temp4", disabled = true }
        temp1 = { label = "Temp1", disabled = true }
        temp2 = { label = "Temp2", disabled = true }
        temp3 = { label = "Temp3", disabled = true }
        fan2 = { label = "Fan2", disabled = true }
        fan4 = { label = "Fan4", disabled = true }
        temp5 = { label = "Temp5", disabled = true }

        # NVMe 970 EVO
        [settings.${nvme_970evo}]
        name = "Samsung SSD 970 EVO Plus 1TB"
        disable = false
        [settings.${nvme_970evo}.channel_settings]
        temp3 = { disabled = true }
        temp2 = { disabled = true }

        # NVMe 990 PRO
        [settings.${nvme_990pro}]
        name = "Samsung SSD 990 PRO 4TB"
        disable = false
        [settings.${nvme_990pro}.channel_settings]
        temp3 = { disabled = true }
        temp2 = { disabled = true }

        # Disabled Devices
        [settings.${ethernet}]
        name = "r8169_0_900:00"
        disable = true
        [settings.${ethernet}.channel_settings]

        [settings.${spd_1}]
        name = "spd5118"
        disable = true
        [settings.${spd_1}.channel_settings]

        [settings.${spd_2}]
        name = "spd5118"
        disable = true
        [settings.${spd_2}.channel_settings]

        [settings.${gigabyte_wmi}]
        name = "gigabyte_wmi"
        disable = true
        [settings.${gigabyte_wmi}.channel_settings]


        ###  Custom Sensors Logic ---
        # Sensor 1: Mixed CPU + GPU + Mixed NVMe
        [[custom_sensors]]
        id = "sensor1"
        cs_type = "Mix"
        mix_function = "Max"

        [[custom_sensors.sources]]
        temp_source = { temp_name = "temp1", device_uid = "${cpu}" }
        weight = 1

        [[custom_sensors.sources]]
        temp_source = { temp_name = "temp2", device_uid = "${gpu}" }
        weight = 1

        [[custom_sensors.sources]]
        temp_source = { temp_name = "sensor2", device_uid = "${cust_sens_dev}" }
        weight = 1

        # Sensor 2: Mixed NVMe Drives
        [[custom_sensors]]
        id = "sensor2"
        cs_type = "Mix"
        mix_function = "Max"

        [[custom_sensors.sources]]
        temp_source = { temp_name = "temp1", device_uid = "${nvme_990pro}" }
        weight = 1

        [[custom_sensors.sources]]
        temp_source = { temp_name = "temp1", device_uid = "${nvme_970evo}" }
        weight = 1

        ###  Legacy Compatibility ---
        [legacy690]
        # Leave empty to disable
      '';
  };
}
