{
  ...
}: {
  # --- NIXOS MODULE ---
  flake.modules.nixos.gwen-t1 = {
    options,
    config,
    lib,
    ...
  }: {
    config = lib.mkIf ( config.programs.coolercontrol.enable or false ) (
      let
        id = config.host.coolercontrol.id;
      in {
        environment.etc = {
          "coolercontrol/config.toml" = {
            mode = "0644";
            # Stupid extension... Nix highlighting is close enough to make toml readable
            text = lib.replaceStrings ["# syntax: nix\n"] [""] ''
              # syntax: nix
              # ---------------------------------------------------------
              # COOLERCONTROL CONFIGURATION
              # Generated by NixOS
              # ---------------------------------------------------------

              # --- General Settings ---
              [settings]
              apply_on_boot = true
              liquidctl_integration = true
              hide_duplicate_devices = true
              no_init = false
              startup_delay = 2
              thinkpad_full_speed = false
              compress_payload = false
              poll_rate = 1.0
              drivetemp_suspend = true

              # --- Profiles ---
              [[profiles]]
              uid = "${id.profiles.aio_fans}"
              name = "AIO Fans"
              p_type = "Graph"
              speed_profile = [[0.0, 40], [70.0, 40], [80.0, 50], [85.0, 60], [90.0, 80], [105.0, 80], [106.0, 100]]
              temp_source = { temp_name = "${id.sensors.system}", device_uid = "${id.devices.cust_sens_dev}" }
              temp_min = 0.0
              temp_max = 106.0
              function_uid = "${id.functions.exp_mov_avg}"
              offset_profile = []


              # --- Functions ---
              [[functions]]
              uid = "${id.functions.exp_mov_avg}"
              name = "ExpMovAvg"
              f_type = "ExponentialMovingAvg"
              duty_minimum = 2
              duty_maximum = 100
              sample_window = 12

              # --- Device Settings ---
              [device-settings]

              # IT8696 Fan Controller
              [device-settings.${id.devices.it8696}]
              fan5 = { speed_fixed = 100 }                       # CPU Pump
              fan1 = { profile_uid = "${id.profiles.aio_fans}" } # Radiator Fans

              # --- Individual Device Configs ---
              # CPU
              [settings.${id.devices.cpu}]
              name = "AMD Ryzen 7 9800X3D 8-Core Processor"
              disable = false
              [settings.${id.devices.cpu}.channel_settings]
              temp3 = { label = "CPU Temp Tccd1", disabled = true }
              "CPU Freq Max" = { label = "CPU Freq Max", disabled = true }
              "CPU Freq Avg" = { label = "CPU Freq Avg", disabled = true }
              "CPU Freq Min" = { label = "CPU Freq Min", disabled = true }

              # AMD GPU
              [settings.${id.devices.gpu}]
              name = "amdgpu"
              disable = false
              [settings.${id.devices.gpu}.channel_settings]
              freq2 = { label = "GPU Mem", disabled = false }
              fan1 = { label = "GPU Fans", disabled = false, extension = { hw_fan_curve_enabled = true } }
              temp1 = { label = "GPU Temp Edge", disabled = true }
              temp3 = { label = "GPU Temp Mem", disabled = true }

              # ACPITZ
              [settings.${id.devices.acpitz}]
              name = "acpitz"
              disable = true
              [settings.${id.devices.acpitz}.channel_settings]

              # IT8696 (Fan Controller)
              [settings.${id.devices.it8696}]
              name = "it8696"
              disable = false
              [settings.${id.devices.it8696}.channel_settings]
              fan3 = { label = "Fan3", disabled = false } # NVME Fan
              temp4 = { label = "Temp4", disabled = true }
              temp1 = { label = "Temp1", disabled = true }
              temp2 = { label = "Temp2", disabled = true }
              temp3 = { label = "Temp3", disabled = true }
              fan2 = { label = "Fan2", disabled = true }
              fan4 = { label = "Fan4", disabled = true }
              temp5 = { label = "Temp5", disabled = true }

              # NVMe 970 EVO
              [settings.${id.devices.nvme_970evo}]
              name = "Samsung SSD 970 EVO Plus 1TB"
              disable = false
              [settings.${id.devices.nvme_970evo}.channel_settings]
              temp3 = { disabled = true }
              temp2 = { disabled = true }

              # NVMe 990 PRO
              [settings.${id.devices.nvme_990pro}]
              name = "Samsung SSD 990 PRO 4TB"
              disable = false
              [settings.${id.devices.nvme_990pro}.channel_settings]
              temp3 = { disabled = true }
              temp2 = { disabled = true }

              # Disabled Devices
              [settings.${id.devices.ethernet}]
              name = "r8169_0_900:00"
              disable = true
              [settings.${id.devices.ethernet}.channel_settings]

              [settings.${id.devices.spd_1}]
              name = "spd5118"
              disable = true
              [settings.${id.devices.spd_1}.channel_settings]

              [settings.${id.devices.spd_2}]
              name = "spd5118"
              disable = true
              [settings.${id.devices.spd_2}.channel_settings]

              [settings.${id.devices.gigabyte_wmi}]
              name = "gigabyte_wmi"
              disable = true
              [settings.${id.devices.gigabyte_wmi}.channel_settings]


              # --- Custom Sensors Logic ---
              # Sensor 1: Mixed CPU + GPU + Mixed NVMe
              [[custom_sensors]]
              id = "${id.sensors.system}"
              cs_type = "Mix"
              mix_function = "Max"

              [[custom_sensors.sources]]
              temp_source = { temp_name = "temp1", device_uid = "${id.devices.cpu}" }
              weight = 1

              [[custom_sensors.sources]]
              temp_source = { temp_name = "temp2", device_uid = "${id.devices.gpu}" }
              weight = 1

              [[custom_sensors.sources]]
              temp_source = { temp_name = "${id.sensors.nvme}", device_uid = "${id.devices.cust_sens_dev}" }
              weight = 1

              # Sensor 2: Mixed NVMe Drives
              [[custom_sensors]]
              id = "${id.sensors.nvme}"
              cs_type = "Mix"
              mix_function = "Max"

              [[custom_sensors.sources]]
              temp_source = { temp_name = "temp1", device_uid = "${id.devices.nvme_990pro}" }
              weight = 1

              [[custom_sensors.sources]]
              temp_source = { temp_name = "temp1", device_uid = "${id.devices.nvme_970evo}" }
              weight = 1

              # --- Legacy Compatibility ---
              [legacy690]
              # Leave empty to disable
            '';
          };
        };
      }
    );
  };
}